const D=window.KAOYAN_DATA;
const G=window.KAOYAN_GENERATED||{lexicon:{},sentences:{}};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const shuffle=a=>[...a].sort(()=>Math.random()-.5), sample=(a,n)=>shuffle(a).slice(0,n);
const yearsAll=[2023,2024,2025,2026];
const store={get(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set(k,v){localStorage.setItem(k,JSON.stringify(v))}};
let P=store.get('kaoyanProgressV2',{wrong:{},seen:{},done:0,sentSeen:{}}), years=new Set(yearsAll), currentMode='', session=null;
let zhCache=store.get('kaoyanZhCacheV2',{});
const lexicon=[...D.vocab,...D.phrases];
function save(){store.set('kaoyanProgressV2',P);updateHome()}
function saveZh(){store.set('kaoyanZhCacheV2',zhCache)}
function markVocab(id,ok){P.seen[id]=(P.seen[id]||0)+1;P.done++;if(ok){if(P.wrong[id])P.wrong[id]=Math.max(0,P.wrong[id]-1)}else P.wrong[id]=(P.wrong[id]||0)+2;save()}
function markSentence(id,ok=true){P.sentSeen[id]=(P.sentSeen[id]||0)+1;P.done++;save()}
function updateHome(){const w=Object.values(P.wrong).filter(x=>x>0).length;$('#statWords').textContent=D.stats.vocab_words.toLocaleString();$('#statPhrases').textContent=D.stats.phrases.toLocaleString();$('#statSent').textContent=D.stats.sentences_complete_8plus.toLocaleString();$('#statLong').textContent=D.stats.sentences_long_15plus.toLocaleString();$('#statWrong').textContent=w;$('#statDone').textContent=(P.done||0).toLocaleString();const seen=Object.keys(P.seen).length+Object.keys(P.sentSeen).length,total=lexicon.length+D.sentences.length;const penalty=Object.values(P.wrong).reduce((a,b)=>a+b,0);const pct=Math.max(0,Math.min(100,Math.round((seen/total*100)-Math.min(25,penalty*.2))));$('#masteryPct').textContent=pct+'%';$('#masteryBar').style.width=pct+'%';$('#corpusNote').innerHTML=`语料审计：四套 PDF 共抽取 <b>${D.stats.raw_word_tokens.toLocaleString()}</b> 个英文词 token、<b>${D.stats.raw_unique_surface_forms.toLocaleString()}</b> 个不同表层词形。剔除 a/an/the 等基础功能词、明显人名地名和试卷说明后，默认训练库为 <b>${D.stats.lexical_total.toLocaleString()}</b> 个词汇/词组；完整句库 <b>${D.stats.sentences_complete_8plus}</b> 句，其中 <b>${D.stats.sentences_long_15plus}</b> 句为 15 词以上长句。`}
function go(mode){currentMode=mode;$('#home').classList.remove('active');$('#trainer').classList.add('active');const meta={match:['VOCAB MATCH','词汇 / 词组连线'],'build-en':['SENTENCE BUILD','汉译 → 英文拼句'],'build-zh':['SENTENCE BUILD','英文 → 中文拼译'],free:['FREE TRANSLATION','无提示汉译'],structure:['SENTENCE ANATOMY','长难句拆骨架'],review:['CONTEXT REVIEW','错题强化 · 真题语境填词']}[mode];$('#modeEyebrow').textContent=meta[0];$('#modeTitle').textContent=meta[1];renderYears();startMode()}
function renderYears(){$('#yearFilter').innerHTML=yearsAll.map(y=>`<button class="chip ${years.has(y)?'active':''}" data-y="${y}">${y}</button>`).join('');$$('[data-y]').forEach(b=>b.onclick=()=>{const y=+b.dataset.y;if(years.has(y)&&years.size>1)years.delete(y);else years.add(y);renderYears();startMode()})}
function yearsMatch(x){const ys=x.years||[x.year];return ys.some(y=>years.has(y))}
function startMode(){if(currentMode==='match')startMatch();else if(currentMode==='review')startReview();else startSentenceMode()}
const providers=['https://lingva.ml','https://translate.jae.fi','https://lingva.garudalinux.org','https://lingva.lunar.icu','https://translate.nexo.moe'];
function hasHan(s){return /[\u3400-\u9fff]/.test(s||'')}
async function fetchTimed(url,ms=6500){const ctl=new AbortController(),t=setTimeout(()=>ctl.abort(),ms);try{return await fetch(url,{signal:ctl.signal,cache:'force-cache'})}finally{clearTimeout(t)}}
async function translateText(text){text=(text||'').trim();if(!text)return '';const key='t|'+text;if(zhCache[key])return zhCache[key];for(const base of providers){try{const r=await fetchTimed(`${base}/api/v1/en/zh/${encodeURIComponent(text)}`);if(!r.ok)continue;const j=await r.json();const z=(j.translation||'').trim();if(hasHan(z)){zhCache[key]=z;saveZh();return z}}catch(e){}}
try{const q=text.slice(0,450);const r=await fetchTimed(`https://api.mymemory.translated.net/get?q=${encodeURIComponent(q)}&langpair=en|zh-CN`,7000);if(r.ok){const j=await r.json();const z=(j.responseData?.translatedText||'').trim();if(hasHan(z)){zhCache[key]=z;saveZh();return z}}}catch(e){}
return ''}
async function zhLex(v){if(v.zh)return v.zh;if(G.lexicon?.[v.term])return cleanGloss(G.lexicon[v.term]);const k='lex|'+v.term;if(zhCache[k])return zhCache[k];let z=await translateText(v.term);if(z){z=cleanGloss(z);zhCache[k]=z;saveZh();return z}return '释义暂不可用'}
function cleanGloss(z){return String(z||'').replace(/^(n\.|v\.|a\.|adj\.|adv\.|prep\.|conj\.|pron\.|num\.|art\.)\s*/i,'').split(/\n/)[0].slice(0,90)}
async function zhSentence(s){if(s.zh)return s.zh;if(G.sentences?.[s.id])return G.sentences[s.id];const k='sent|'+s.id;if(zhCache[k])return zhCache[k];const z=await translateText(s.en);if(z){zhCache[k]=z;saveZh();return z}return ''}
function weightedVocab(){const pool=lexicon.filter(yearsMatch);let bag=[];pool.forEach(v=>{let wt=1+(P.wrong[v.id]||0)*4+(P.seen[v.id]?0:2);for(let i=0;i<wt;i++)bag.push(v)});let out=[],used=new Set();for(const v of shuffle(bag)){if(!used.has(v.id)){out.push(v);used.add(v.id)}if(out.length===Math.min(50,pool.length))break}return out}
function startMatch(){session={items:weightedVocab(),group:0,score:0,answered:0};renderMatchGroup()}
async function renderMatchGroup(){const start=session.group*10,items=session.items.slice(start,start+10);if(!items.length){$('#trainerBody').innerHTML=`<div class="panel"><h2>本轮完成</h2><p>正确 ${session.score} / ${session.answered}</p><div class="actions"><button class="primary" id="again">再来 50 个</button><button class="secondary" id="wrongOnly">去错题强化</button></div></div>`;$('#again').onclick=startMatch;$('#wrongOnly').onclick=()=>go('review');return}$('#trainerBody').innerHTML='<div class="panel loading"><b>正在准备这一组的中文释义…</b><span>首次遇到未缓存词条时会稍等；之后会直接读取本机缓存。</span></div>';const zh=await Promise.all(items.map(zhLex));if(currentMode!=='match')return;const right=shuffle(items.map((x,i)=>({id:x.id,zh:zh[i]})));session.leftSel=null;session.rightSel=null;session.matched=new Set();$('#trainerBody').innerHTML=`<div class="panel"><div class="session-line"><span>本轮 ${session.items.length} · 第 ${session.group+1}/${Math.ceil(session.items.length/10)} 组</span><span>正确 ${session.score} / ${session.answered}</span></div><div class="match-grid"><div class="match-col">${items.map((x,i)=>`<button class="match-item" data-side="l" data-id="${x.id}"><b>${i+1}.</b> ${x.term}<small style="display:block;color:#8a8f8b;margin-top:3px">${(x.years||[x.year]).join('/')} · ${x.type==='phrase'?'词组':'词汇'}</small></button>`).join('')}</div><div class="match-col">${right.map((x,i)=>`<button class="match-item" data-side="r" data-id="${x.id}"><b>${String.fromCharCode(97+i)}.</b> ${x.zh}</button>`).join('')}</div></div><div class="actions"><button class="secondary" id="nextGroup" disabled>下一组</button></div></div>`;$$('.match-item').forEach(b=>b.onclick=()=>selectMatch(b));$('#nextGroup').onclick=()=>{session.group++;renderMatchGroup()}}
function selectMatch(b){if(b.classList.contains('done'))return;const side=b.dataset.side;$$(`[data-side="${side}"]`).forEach(x=>x.classList.remove('selected'));b.classList.add('selected');session[side==='l'?'leftSel':'rightSel']=b;if(session.leftSel&&session.rightSel){const ok=session.leftSel.dataset.id===session.rightSel.dataset.id;session.answered++;markVocab(session.leftSel.dataset.id,ok);if(ok){session.score++;[session.leftSel,session.rightSel].forEach(x=>{x.classList.remove('selected');x.classList.add('done')});session.matched.add(session.leftSel.dataset.id)}else{[session.leftSel,session.rightSel].forEach(x=>{x.classList.add('wrongflash');setTimeout(()=>x.classList.remove('wrongflash','selected'),350)})}session.leftSel=session.rightSel=null;const groupN=Math.min(10,session.items.length-session.group*10);if(session.matched.size===groupN)$('#nextGroup').disabled=false}}
function sentencePool(){let p=D.sentences.filter(s=>years.has(s.year));if(currentMode==='structure')p=p.filter(s=>s.is_long);return p}
function startSentenceMode(){const pool=sentencePool();if(!pool.length)return;session={pool:shuffle(pool),idx:0};renderSentence()}
function nextSentence(){session.idx=(session.idx+1)%session.pool.length;renderSentence()}
async function renderSentence(){const s=session.pool[session.idx];if(currentMode==='build-en')await renderBuilder(s,'en');else if(currentMode==='build-zh')await renderBuilder(s,'zh');else if(currentMode==='free')await renderFree(s);else if(currentMode==='structure')await renderStructure(s)}
function autoEnChunks(text){let t=text.replace(/\s+/g,' ').trim();let parts=t.split(/(?<=[,;:])\s+|\s+(?=(?:but|and|while|although|because|if|when|which|who|that|where|as|since|so that|rather than|instead of|to)\b)/i).map(x=>x.trim()).filter(Boolean);if(parts.length<3){const words=t.split(' ');const n=Math.max(5,Math.ceil(words.length/5));parts=[];for(let i=0;i<words.length;i+=n)parts.push(words.slice(i,i+n).join(' '))}return parts.slice(0,12)}
function autoZhChunks(z){let parts=z.split(/(?<=[，；：。！？])/).map(x=>x.trim()).filter(x=>x.length>1);if(parts.length<3){const cuts=['但是','因此','同时','而且','因为','尽管','从而','并且','以及','这意味着','其中'];let t=z;for(const c of cuts)t=t.replaceAll(c,'|'+c);parts=t.split('|').map(x=>x.trim()).filter(x=>x.length>1)}if(parts.length<3&&z.length>24){const n=Math.ceil(z.length/4);parts=[];for(let i=0;i<z.length;i+=n)parts.push(z.slice(i,i+n))}return parts.slice(0,12)}
async function renderBuilder(s,lang){$('#trainerBody').innerHTML='<div class="panel loading"><b>正在准备真题句…</b></div>';const z=await zhSentence(s);if(!z){return showTranslateError(s)};const correct=lang==='en'?(s.enChunks||autoEnChunks(s.en)):(s.zhChunks||autoZhChunks(z));const fixedDist=lang==='en'?['without changing the original conclusion','in spite of every possible outcome']:['这并不意味着所有问题都已解决','与此同时这一结论完全没有限制'];const distract=(lang==='en'?s.enDistractors:s.zhDistractors)||fixedDist;const prompt=lang==='en'?z:s.en;session.answer=[];session.correct=correct;const bank=shuffle([...correct,...distract]).map((t,i)=>({key:'t'+i,text:t}));session.bank=bank;$('#trainerBody').innerHTML=`<div class="panel"><div class="sentence-meta"><span>${s.year} 英语一 · ${s.source} · P${s.page||'?'}</span><span>第 ${session.idx+1}/${session.pool.length} 句</span></div><div class="${lang==='en'?'prompt-cn':'prompt-en'}">${prompt}</div><div class="answer-zone" id="answerZone"><span style="color:#9b9b94">点击下方词块组成答案</span></div><div class="token-bank">${bank.map(t=>`<button class="token" data-key="${t.key}">${t.text}</button>`).join('')}</div><div class="actions"><button class="secondary" id="undo">撤回一步</button><button class="primary" id="checkBuild">检查</button><button class="secondary" id="nextSent">换一句</button></div><div id="buildFeedback"></div><div class="translation-note">${s.manual_translation?'Part C 人工校对译文':'非 Part C 句子的中文为训练参考译文；允许按意义理解，不要求逐字一致。'}</div></div>`;$$('.token').forEach(b=>b.onclick=()=>{if(b.classList.contains('used'))return;session.answer.push({key:b.dataset.key,text:b.textContent});b.classList.add('used');paintAnswer()});$('#undo').onclick=()=>{const x=session.answer.pop();if(x){document.querySelector(`[data-key="${x.key}"]`)?.classList.remove('used');paintAnswer()}};$('#checkBuild').onclick=()=>checkBuilder(s);$('#nextSent').onclick=nextSentence}
function paintAnswer(){const z=$('#answerZone');z.innerHTML=session.answer.length?session.answer.map((x,i)=>`<button class="token in-answer" data-ai="${i}">${x.text}</button>`).join(''):'<span style="color:#9b9b94">点击下方词块组成答案</span>';$$('[data-ai]').forEach(b=>b.onclick=()=>{const i=+b.dataset.ai,x=session.answer.splice(i,1)[0];document.querySelector(`[data-key="${x.key}"]`)?.classList.remove('used');paintAnswer()})}
function checkBuilder(s){const ans=session.answer.map(x=>x.text),target=session.correct;const ok=ans.length===target.length&&ans.every((x,i)=>x===target[i]);markSentence(s.id,ok);$('#buildFeedback').innerHTML=`<div class="feedback ${ok?'good':'warn'}"><b>${ok?'✓ 完全正确':'还差一点'}</b><br>${ok?'语序和意群都对。':'参考顺序：'+target.join(' / ')}</div>`}
function norm(s){return (s||'').toLowerCase().replace(/[\s，。！？；：、“”‘’（）()\[\]【】,.!?;:'"—-]/g,'')}
function dice(a,b){a=norm(a);b=norm(b);if(!a||!b)return 0;const bi=s=>{let r=[];for(let i=0;i<s.length-1;i++)r.push(s.slice(i,i+2));return r};let A=bi(a),B=bi(b),m=0,used=new Array(B.length).fill(false);for(const x of A){let j=B.findIndex((y,k)=>!used[k]&&y===x);if(j>=0){used[j]=true;m++}}return (2*m)/(A.length+B.length||1)}
function semanticGroups(z){const chunks=autoZhChunks(z);return chunks.map(c=>{const n=c.replace(/[，。！？；：]/g,'').trim();return [n,n.replace(/^因此|^同时|^而且|^但是|^因为|^尽管/,'')] }).filter(g=>g[0].length>=3)}
function semanticScore(text,groups){const n=norm(text),hits=[];groups.forEach(g=>hits.push(g.some(x=>norm(x).length>=2&&n.includes(norm(x)))));return {coverage:groups.length?hits.filter(Boolean).length/groups.length:0,hits}}
async function renderFree(s){$('#trainerBody').innerHTML='<div class="panel loading"><b>正在准备参考译文…</b></div>';const z=await zhSentence(s);if(!z)return showTranslateError(s);session.refZh=z;$('#trainerBody').innerHTML=`<div class="panel"><div class="sentence-meta"><span>${s.year} 英语一 · ${s.source} · P${s.page||'?'}</span><span>${s.manual_translation?'Part C 人工校对':'宽松语义评分'}</span></div><div class="prompt-en">${s.en}</div><textarea class="textarea" id="freeInput" placeholder="直接写你的中文翻译。不要求和参考译文逐字一致……"></textarea><div class="actions"><button class="primary" id="scoreFree">宽松评分</button><button class="secondary" id="showRef">直接看参考译文</button><button class="secondary" id="nextSent">换一句</button></div><div id="freeFeedback"></div></div>`;$('#scoreFree').onclick=()=>scoreFree(s,z);$('#showRef').onclick=()=>{$('#freeFeedback').innerHTML=`<div class="feedback"><b>参考译文</b><br>${z}<div class="actions"><button class="primary" id="selfGood">我基本会了</button><button class="danger" id="selfBad">这句还不会</button></div></div>`;bindSelf(s)};$('#nextSent').onclick=nextSentence}
function bindSelf(s){const a=$('#selfGood'),b=$('#selfBad');if(a)a.onclick=()=>{markSentence(s.id,true);nextSentence()};if(b)b.onclick=()=>{P.sentSeen[s.id]=(P.sentSeen[s.id]||0)+1;P.done++;save();nextSentence()}}
function scoreFree(s,z){const text=$('#freeInput').value.trim();if(!text)return;const groups=s.groups||semanticGroups(z),sem=semanticScore(text,groups),sim=dice(text,z);let score=Math.round((sem.coverage*.35+sim*.65)*100);if(sim>.62)score=Math.max(score,78);if(sim>.72)score=Math.max(score,86);const cls=score>=80?'good':score>=55?'warn':'bad',label=score>=80?'核心意思基本到位':score>=55?'大意有较多重合':'建议再对照一次参考译文';markSentence(s.id,score>=55);$('#freeFeedback').innerHTML=`<div class="feedback ${cls}"><div class="score-row"><div class="score-ring">${score}</div><div><b>${label}</b><br><small>这是宽松辅助评分，不把参考译文当作唯一答案。你仍可用下方按钮自行修正判定。</small></div></div><hr style="border:0;border-top:1px solid #d7d1c6;margin:14px 0"><b>参考译文</b><br>${z}<div class="actions"><button class="primary" id="selfGood">我认为自己表达正确</button><button class="danger" id="selfBad">这句还不会</button></div></div>`;bindSelf(s)}
function autoStructure(en){const parts=autoEnChunks(en);return parts.map((p,i)=>{let label=i===0?'主干/起始分句':'分句/修饰';if(/^which\b|\bwhich\b/i.test(p))label='定语从句线索';else if(/^who\b|\bwho\b/i.test(p))label='关系从句线索';else if(/^that\b|\bthat\b/i.test(p))label='that 从句线索';else if(/^although\b|^though\b/i.test(p))label='让步关系';else if(/^because\b|^since\b/i.test(p))label='原因关系';else if(/^if\b|^unless\b/i.test(p))label='条件关系';else if(/^while\b|^whereas\b/i.test(p))label='对比/时间关系';else if(/^to\b/i.test(p))label='不定式结构';else if(/^but\b|^and\b/i.test(p))label='并列/转折连接';return `${label}：${p}`})}
async function renderStructure(s){$('#trainerBody').innerHTML='<div class="panel loading"><b>正在准备结构提示…</b></div>';const z=await zhSentence(s);const structure=s.structure||autoStructure(s.en);$('#trainerBody').innerHTML=`<div class="panel"><div class="sentence-meta"><span>${s.year} 英语一 · ${s.source} · P${s.page||'?'}</span><span>${s.word_count} words</span></div><div class="prompt-en">${s.en}</div><button class="primary" id="revealStruct">显示句子骨架</button><div id="structArea"></div><div class="actions"><button class="secondary" id="nextSent">换一句</button></div></div>`;$('#revealStruct').onclick=()=>{$('#structArea').innerHTML=`<div class="structure-list">${structure.map((x,i)=>`<div class="structure-part"><b>${i+1}.</b> ${x}</div>`).join('')}</div>${z?`<div class="feedback"><b>参考译文</b><br>${z}</div>`:''}<div class="translation-note">${s.structure?'Part C 人工结构标注':'自动结构提示用于训练抓主干；复杂句最终以语义和上下文判断为准。'}</div>`;markSentence(s.id,true)};$('#nextSent').onclick=nextSentence}
function wrongPool(){const ids=Object.entries(P.wrong).filter(([,n])=>n>0).sort((a,b)=>b[1]-a[1]).map(([id])=>id);let p=ids.map(id=>lexicon.find(v=>v.id===id)).filter(Boolean).filter(yearsMatch);if(p.length<4){const extra=lexicon.filter(v=>yearsMatch(v)&&!ids.includes(v.id));p=[...p,...sample(extra,Math.min(16,extra.length))]}return p}
function startReview(){session={pool:shuffle(wrongPool()),idx:0,score:0};renderReview()}
async function renderReview(){const pool=session.pool;if(!pool.length){$('#trainerBody').innerHTML='<div class="panel empty">目前没有错题。先去做一轮词汇连线吧。</div>';return}const v=pool[session.idx%pool.length];$('#trainerBody').innerHTML='<div class="panel loading"><b>正在准备真题语境题…</b></div>';let distract=sample(lexicon.filter(x=>x.id!==v.id&&x.type===v.type&&yearsMatch(x)),3),options=shuffle([v,...distract]);const zh=await Promise.all(options.map(zhLex));const zmap=Object.fromEntries(options.map((o,i)=>[o.id,zh[i]]));const esc=v.term.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');let blank=v.context.replace(new RegExp(esc,'i'),'_____');if(blank===v.context)blank=v.context+'  →  _____';$('#trainerBody').innerHTML=`<div class="panel"><div class="session-line"><span>${v.year} · ${v.source}${v.page?' · P'+v.page:''}</span><span>${P.wrong[v.id]>0?'错题权重 '+P.wrong[v.id]:'巩固题'}</span></div><div class="context-box">${blank}</div><div class="option-grid">${options.map(x=>`<button class="option" data-id="${x.id}"><b>${x.term}</b><br><small>${zmap[x.id]}</small></button>`).join('')}</div><div id="reviewFeedback"></div><div class="actions"><button class="secondary" id="nextReview">下一题</button></div></div>`;$$('.option').forEach(b=>b.onclick=()=>{if($$('.option.correct,.option.wrong').length)return;const ok=b.dataset.id===v.id;b.classList.add(ok?'correct':'wrong');document.querySelector(`.option[data-id="${v.id}"]`)?.classList.add('correct');markVocab(v.id,ok);$('#reviewFeedback').innerHTML=`<div class="feedback ${ok?'good':'warn'}"><b>${ok?'✓ 正确':'答案是 '+v.term}</b><br>${v.context}</div>`});$('#nextReview').onclick=()=>{session.idx++;renderReview()}}
function showTranslateError(s){$('#trainerBody').innerHTML=`<div class="panel errorbox"><b>这一句的在线参考译文暂时没有取到。</b><p>原句仍已收录在本地语料库中。你可以换一句，或稍后重试；Part C 人工校对句不依赖在线翻译。</p><div class="prompt-en">${s.en}</div><div class="actions"><button class="primary" id="retry">重试</button><button class="secondary" id="nextSent">换一句</button></div></div>`;$('#retry').onclick=renderSentence;$('#nextSent').onclick=nextSentence}
$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$('#backHome').onclick=()=>{$('#trainer').classList.remove('active');$('#home').classList.add('active');updateHome()};$('#resetProgress').onclick=()=>{if(confirm('确定清空本机的所有练习记录吗？')){localStorage.removeItem('kaoyanProgressV2');P=store.get('kaoyanProgressV2',{wrong:{},seen:{},done:0,sentSeen:{}});updateHome()}};updateHome();
