const D=window.KAOYAN_DATA;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const shuffle=a=>[...a].sort(()=>Math.random()-.5);
const sample=(a,n)=>shuffle(a).slice(0,n);
const store={get(){try{return JSON.parse(localStorage.getItem('kaoyanProgress'))||{wrong:{},seen:{},done:0,sentSeen:{}}}catch{return{wrong:{},seen:{},done:0,sentSeen:{}}}},set(v){localStorage.setItem('kaoyanProgress',JSON.stringify(v))}};
let P=store.get(), currentMode='', years=new Set([2023,2024,2025,2026]), session=null;
function save(){store.set(P);updateHome()}
function markVocab(id,ok){P.seen[id]=(P.seen[id]||0)+1;P.done++;if(ok){if(P.wrong[id])P.wrong[id]=Math.max(0,P.wrong[id]-1)}else P.wrong[id]=(P.wrong[id]||0)+2;save()}
function markSentence(id,ok=true){P.sentSeen[id]=(P.sentSeen[id]||0)+1;P.done++;save()}
function updateHome(){const w=Object.values(P.wrong).filter(x=>x>0).length;$('#statVocab').textContent=D.vocab.length;$('#statSent').textContent=D.sentences.length;$('#statWrong').textContent=w;$('#statDone').textContent=P.done||0;const seen=Object.keys(P.seen).length+Object.keys(P.sentSeen).length,total=D.vocab.length+D.sentences.length;const penalty=Object.values(P.wrong).reduce((a,b)=>a+b,0);const pct=Math.max(0,Math.min(100,Math.round((seen/total*100)-Math.min(25,penalty*.35))));$('#masteryPct').textContent=pct+'%';$('#masteryBar').style.width=pct+'%'}
function go(mode){currentMode=mode;$('#home').classList.remove('active');$('#trainer').classList.add('active');const meta={match:['VOCAB MATCH','词汇 / 词组连线'], 'build-en':['SENTENCE BUILD','汉译 → 英文拼句'],'build-zh':['SENTENCE BUILD','英文 → 中文拼译'],free:['FREE TRANSLATION','无提示汉译'],structure:['SENTENCE ANATOMY','长难句拆骨架'],review:['CONTEXT REVIEW','错题强化 · 真题语境填词']}[mode];$('#modeEyebrow').textContent=meta[0];$('#modeTitle').textContent=meta[1];renderYears();startMode()}
function renderYears(){$('#yearFilter').innerHTML=[2023,2024,2025,2026].map(y=>`<button class="chip ${years.has(y)?'active':''}" data-y="${y}">${y}</button>`).join('');$$('[data-y]').forEach(b=>b.onclick=()=>{const y=+b.dataset.y;if(years.has(y)&&years.size>1)years.delete(y);else years.add(y);renderYears();startMode()})}
function startMode(){if(currentMode==='match')startMatch();else if(currentMode==='review')startReview();else startSentenceMode()}
function weightedVocab(){const raw=D.vocab.filter(v=>years.has(v.year));const best=new Map();raw.forEach(v=>{const k=v.term.toLowerCase()+'|'+v.zh;const old=best.get(k);const score=x=>(P.wrong[x.id]||0)*10-(P.seen[x.id]||0);if(!old||score(v)>score(old))best.set(k,v)});const pool=[...best.values()];let bag=[];pool.forEach(v=>{let wt=1+(P.wrong[v.id]||0)*4+(P.seen[v.id]?0:2);for(let i=0;i<wt;i++)bag.push(v)});let out=[],used=new Set();for(const v of shuffle(bag)){if(!used.has(v.id)){out.push(v);used.add(v.id)}if(out.length===Math.min(50,pool.length))break}return out}
function startMatch(){session={items:weightedVocab(),group:0,score:0,answered:0};renderMatchGroup()}
function renderMatchGroup(){const start=session.group*10,items=session.items.slice(start,start+10);if(!items.length){$('#trainerBody').innerHTML=`<div class="panel"><h2>本轮完成</h2><p>正确 ${session.score} / ${session.answered}</p><div class="actions"><button class="primary" id="again">再来 50 个</button><button class="secondary" id="wrongOnly">去错题强化</button></div></div>`;$('#again').onclick=startMatch;$('#wrongOnly').onclick=()=>go('review');return}const right=shuffle(items.map(x=>({id:x.id,zh:x.zh})));session.leftSel=null;session.rightSel=null;session.matched=new Set();$('#trainerBody').innerHTML=`<div class="panel"><div class="session-line"><span>本轮 50 · 第 ${session.group+1}/5 组</span><span>正确 ${session.score} / ${session.answered}</span></div><div class="match-grid"><div class="match-col">${items.map((x,i)=>`<button class="match-item" data-side="l" data-id="${x.id}"><b>${i+1}.</b> ${x.term}<small style="display:block;color:#8a8f8b;margin-top:3px">${x.year} · ${x.type==='phrase'?'词组':'词汇'}</small></button>`).join('')}</div><div class="match-col">${right.map((x,i)=>`<button class="match-item" data-side="r" data-id="${x.id}"><b>${String.fromCharCode(97+i)}.</b> ${x.zh}</button>`).join('')}</div></div><div class="actions"><button class="secondary" id="nextGroup" disabled>下一组</button></div></div>`;$$('.match-item').forEach(b=>b.onclick=()=>selectMatch(b));$('#nextGroup').onclick=()=>{session.group++;renderMatchGroup()}}
function selectMatch(b){if(b.classList.contains('done'))return;const side=b.dataset.side;$$(`[data-side="${side}"]`).forEach(x=>x.classList.remove('selected'));b.classList.add('selected');session[side==='l'?'leftSel':'rightSel']=b;if(session.leftSel&&session.rightSel){const ok=session.leftSel.dataset.id===session.rightSel.dataset.id;session.answered++;markVocab(session.leftSel.dataset.id,ok);if(ok){session.score++;[session.leftSel,session.rightSel].forEach(x=>{x.classList.remove('selected');x.classList.add('done')});session.matched.add(session.leftSel.dataset.id)}else{[session.leftSel,session.rightSel].forEach(x=>{x.classList.add('wrongflash');setTimeout(()=>x.classList.remove('wrongflash','selected'),350)})}session.leftSel=session.rightSel=null;if(session.matched.size===Math.min(10,session.items.length-session.group*10))$('#nextGroup').disabled=false}}
function sentencePool(){return D.sentences.filter(s=>years.has(s.year))}
function startSentenceMode(){const pool=sentencePool();if(!pool.length)return;session={pool:shuffle(pool),idx:0};renderSentence()}
function nextSentence(){session.idx=(session.idx+1)%session.pool.length;renderSentence()}
function renderSentence(){const s=session.pool[session.idx];if(currentMode==='build-en')renderBuilder(s,'en');else if(currentMode==='build-zh')renderBuilder(s,'zh');else if(currentMode==='free')renderFree(s);else if(currentMode==='structure')renderStructure(s)}
function renderBuilder(s,lang){const prompt=lang==='en'?s.zh:s.en, correct=lang==='en'?s.enChunks:s.zhChunks, distract=lang==='en'?s.enDistractors:s.zhDistractors;session.answer=[];session.correct=correct;const bank=shuffle([...correct,...distract]).map((t,i)=>({key:'t'+i,text:t}));session.bank=bank;$('#trainerBody').innerHTML=`<div class="panel"><div class="sentence-meta"><span>${s.year} 英语一 · Part C · ${s.number}</span><span>第 ${session.idx+1}/${session.pool.length} 句</span></div><div class="${lang==='en'?'prompt-cn':'prompt-en'}">${prompt}</div><div class="answer-zone" id="answerZone"><span style="color:#9b9b94">点击下方词块组成答案</span></div><div class="token-bank">${bank.map(t=>`<button class="token" data-key="${t.key}">${t.text}</button>`).join('')}</div><div class="actions"><button class="secondary" id="undo">撤回一步</button><button class="primary" id="checkBuild">检查</button><button class="secondary" id="nextSent">换一句</button></div><div id="buildFeedback"></div></div>`;$$('.token').forEach(b=>b.onclick=()=>{if(b.classList.contains('used'))return;session.answer.push({key:b.dataset.key,text:b.textContent});b.classList.add('used');paintAnswer()});$('#undo').onclick=()=>{const x=session.answer.pop();if(x){document.querySelector(`[data-key="${x.key}"]`).classList.remove('used');paintAnswer()}};$('#checkBuild').onclick=()=>checkBuilder(s);$('#nextSent').onclick=nextSentence}
function paintAnswer(){const z=$('#answerZone');z.innerHTML=session.answer.length?session.answer.map((x,i)=>`<button class="token in-answer" data-ai="${i}">${x.text}</button>`).join(''):'<span style="color:#9b9b94">点击下方词块组成答案</span>';$$('[data-ai]').forEach(b=>b.onclick=()=>{const i=+b.dataset.ai,x=session.answer.splice(i,1)[0];document.querySelector(`[data-key="${x.key}"]`).classList.remove('used');paintAnswer()})}
function checkBuilder(s){const ans=session.answer.map(x=>x.text),target=session.correct;let ok=ans.length===target.length&&ans.every((x,i)=>x===target[i]);markSentence(s.id,ok);const fb=$('#buildFeedback');fb.innerHTML=`<div class="feedback ${ok?'good':'warn'}"><b>${ok?'✓ 完全正确':'还差一点'}</b><br>${ok?'语序和意群都对。':'参考顺序：'+target.join(' / ')}</div>`}
function norm(s){return (s||'').toLowerCase().replace(/[\s，。！？；：、“”‘’（）()\[\]【】,.!?;:'"—-]/g,'')}
function dice(a,b){a=norm(a);b=norm(b);if(!a||!b)return 0;const bi=s=>{let r=[];for(let i=0;i<s.length-1;i++)r.push(s.slice(i,i+2));return r};let A=bi(a),B=bi(b),m=0,used=new Array(B.length).fill(false);for(const x of A){let j=B.findIndex((y,k)=>!used[k]&&y===x);if(j>=0){used[j]=true;m++}}return (2*m)/(A.length+B.length||1)}
function semanticScore(text,groups){const n=norm(text),hits=[];groups.forEach(g=>hits.push(g.some(x=>n.includes(norm(x)))));return {coverage:hits.filter(Boolean).length/groups.length,hits}}
function renderFree(s){$('#trainerBody').innerHTML=`<div class="panel"><div class="sentence-meta"><span>${s.year} 英语一 · Part C · ${s.number}</span><span>宽松语义评分</span></div><div class="prompt-en">${s.en}</div><textarea class="textarea" id="freeInput" placeholder="直接写你的中文翻译。不要求和参考译文逐字一致……"></textarea><div class="actions"><button class="primary" id="scoreFree">宽松评分</button><button class="secondary" id="showRef">直接看参考译文</button><button class="secondary" id="nextSent">换一句</button></div><div id="freeFeedback"></div></div>`;$('#scoreFree').onclick=()=>scoreFree(s);$('#showRef').onclick=()=>{$('#freeFeedback').innerHTML=`<div class="feedback"><b>参考译文</b><br>${s.zh}<div class="actions"><button class="primary" id="selfGood">我基本会了</button><button class="danger" id="selfBad">加入强化</button></div></div>`;bindSelf(s)};$('#nextSent').onclick=nextSentence}
function bindSelf(s){const a=$('#selfGood'),b=$('#selfBad');if(a)a.onclick=()=>{markSentence(s.id,true);nextSentence()};if(b)b.onclick=()=>{P.sentSeen[s.id]=(P.sentSeen[s.id]||0)+1;P.done++;save();nextSentence()}}
function scoreFree(s){const text=$('#freeInput').value.trim();if(!text)return;const sem=semanticScore(text,s.groups),sim=dice(text,s.zh);let score=Math.round((sem.coverage*.78+sim*.22)*100);if(sem.coverage>.85)score=Math.max(score,82);const missing=s.groups.filter((g,i)=>!sem.hits[i]).map(g=>g[0]);let cls=score>=80?'good':score>=58?'warn':'bad',label=score>=80?'含义覆盖很好':score>=58?'大意基本到位':'有较多关键含义遗漏';markSentence(s.id,score>=58);$('#freeFeedback').innerHTML=`<div class="feedback ${cls}"><div class="score-row"><div class="score-ring">${score}</div><div><b>${label}</b><br><small>语义点覆盖 ${Math.round(sem.coverage*100)}%。这里不按逐字匹配判分，近义表达也可通过。</small></div></div>${missing.length?`<div class="missing">建议检查这些意义点：${missing.join('、')}</div>`:''}<hr style="border:0;border-top:1px solid #d7d1c6;margin:14px 0"><b>参考译文</b><br>${s.zh}<div class="actions"><button class="primary" id="selfGood">我认为自己表达正确</button><button class="danger" id="selfBad">这句还不会</button></div></div>`;bindSelf(s)}
function renderStructure(s){$('#trainerBody').innerHTML=`<div class="panel"><div class="sentence-meta"><span>${s.year} 英语一 · Part C · ${s.number}</span></div><div class="prompt-en">${s.en}</div><button class="primary" id="revealStruct">显示句子骨架</button><div id="structArea"></div><div class="actions"><button class="secondary" id="nextSent">换一句</button></div></div>`;$('#revealStruct').onclick=()=>{$('#structArea').innerHTML=`<div class="structure-list">${s.structure.map((x,i)=>`<div class="structure-part"><b>${i+1}.</b> ${x}</div>`).join('')}</div><div class="feedback"><b>参考译文</b><br>${s.zh}</div>`;markSentence(s.id,true)};$('#nextSent').onclick=nextSentence}
function wrongPool(){const ids=Object.entries(P.wrong).filter(([,n])=>n>0).sort((a,b)=>b[1]-a[1]).map(([id])=>id);let p=ids.map(id=>D.vocab.find(v=>v.id===id)).filter(Boolean).filter(v=>years.has(v.year));if(p.length<4){const extra=D.vocab.filter(v=>years.has(v.year)&&!ids.includes(v.id));p=[...p,...sample(extra,Math.min(12,extra.length))]}return p}
function startReview(){session={pool:shuffle(wrongPool()),idx:0,score:0};renderReview()}
function renderReview(){const pool=session.pool;if(!pool.length){$('#trainerBody').innerHTML='<div class="panel empty">目前没有错题。先去做一轮词汇连线吧。</div>';return}const v=pool[session.idx%pool.length],blank=v.context.replace(new RegExp(v.term.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i'),'_____');let distract=sample(D.vocab.filter(x=>x.id!==v.id&&x.type===v.type&&years.has(x.year)),3);let options=shuffle([v,...distract]);$('#trainerBody').innerHTML=`<div class="panel"><div class="session-line"><span>${v.year} · ${v.source}</span><span>${P.wrong[v.id]>0?'错题权重 '+P.wrong[v.id]:'巩固题'}</span></div><div class="context-box">${blank}</div><div class="option-grid">${options.map(x=>`<button class="option" data-id="${x.id}"><b>${x.term}</b><br><small>${x.zh}</small></button>`).join('')}</div><div id="reviewFeedback"></div><div class="actions"><button class="secondary" id="nextReview">下一题</button></div></div>`;$$('.option').forEach(b=>b.onclick=()=>{if($$('.option.correct,.option.wrong').length)return;const ok=b.dataset.id===v.id;b.classList.add(ok?'correct':'wrong');document.querySelector(`.option[data-id="${v.id}"]`).classList.add('correct');markVocab(v.id,ok);$('#reviewFeedback').innerHTML=`<div class="feedback ${ok?'good':'warn'}"><b>${ok?'✓ 正确':'答案是 '+v.term}</b><br>${v.context}</div>`});$('#nextReview').onclick=()=>{session.idx++;renderReview()}}
$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$('#backHome').onclick=()=>{$('#trainer').classList.remove('active');$('#home').classList.add('active');updateHome()};$('#resetProgress').onclick=()=>{if(confirm('确定清空本机的所有练习记录吗？')){localStorage.removeItem('kaoyanProgress');P=store.get();updateHome()}};updateHome();
