const D=window.KAOYAN_DATA;
const G=window.KAOYAN_GENERATED||{lexicon:{},sentences:{}};
const AN=window.KAOYAN_ANATOMY||{precise:[]};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const shuffle=a=>[...a].sort(()=>Math.random()-.5), sample=(a,n)=>shuffle(a).slice(0,n);
const yearsAll=[2023,2024,2025,2026];
const lexicon=[...D.vocab,...D.phrases];
const lexById=Object.fromEntries(lexicon.map(v=>[v.id,v]));
const INTERVALS=[1,2,4,7,15,30,60,120];
const store={get(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set(k,v){localStorage.setItem(k,JSON.stringify(v))}};
const pad=n=>String(n).padStart(2,'0');
function dayKey(d=new Date()){return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
function addDays(key,n){const [y,m,d]=key.split('-').map(Number),x=new Date(y,m-1,d);x.setDate(x.getDate()+n);return dayKey(x)}
function today(){return dayKey()}
function blankRec(){return {seen:0,correct:0,mistakes:0,wrongDebt:0,level:0,due:null,last:null,lastResult:null,lastMode:null}}
function blankProgress(){return {version:4,vocab:{},sentences:{},done:0,daily:{},createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}}
function normalizeProgress(p){p=p||blankProgress();p.version=4;p.vocab=p.vocab||{};p.sentences=p.sentences||{};p.daily=p.daily||{};p.done=p.done||0;return p}
function migrateProgress(){let p=store.get('kaoyanProgressV3',null);if(p)return normalizeProgress(p);p=blankProgress();const old=store.get('kaoyanProgressV2',null);if(old){for(const [id,n] of Object.entries(old.seen||{})){const debt=Math.max(0,old.wrong?.[id]||0);p.vocab[id]={...blankRec(),seen:n,correct:Math.max(0,n-Math.ceil(debt/2)),mistakes:Math.ceil(debt/2),wrongDebt:debt,level:1,due:today(),lastResult:debt<=0};}for(const [id,n] of Object.entries(old.sentSeen||{}))p.sentences[id]={seen:n};p.done=old.done||0;p.migratedFromV2=true;store.set('kaoyanProgressV3',p)}return p}
let P=migrateProgress(), years=new Set(yearsAll), currentMode='', session=null;
let zhCache=store.get('kaoyanZhCacheV3',store.get('kaoyanZhCacheV2',{}));
let dictCache=store.get('kaoyanDictCacheV3',{});
function rec(id){if(!P.vocab[id])P.vocab[id]=blankRec();return P.vocab[id]}
function daily(){const k=today();if(!P.daily[k])P.daily[k]={attempts:0,correct:0,wrong:0,new:0,review:0,sentences:0};return P.daily[k]}
function isDueRecord(r){return !!(r&&r.seen>0&&r.due&&r.due<=today())}
function dueItems(filterYears=false){return lexicon.filter(v=>(!filterYears||yearsMatch(v))&&isDueRecord(P.vocab[v.id])).sort((a,b)=>{const A=P.vocab[a.id],B=P.vocab[b.id];return String(A.due).localeCompare(String(B.due))||(B.wrongDebt||0)-(A.wrongDebt||0)||(A.level||0)-(B.level||0)})}
function wrongItems(filterYears=false){return lexicon.filter(v=>(!filterYears||yearsMatch(v))&&(P.vocab[v.id]?.wrongDebt||0)>0).sort((a,b)=>(P.vocab[b.id].wrongDebt||0)-(P.vocab[a.id].wrongDebt||0)||(P.vocab[b.id].mistakes||0)-(P.vocab[a.id].mistakes||0))}
function save(){P.updatedAt=new Date().toISOString();store.set('kaoyanProgressV3',P);updateHome()}
function saveZh(){store.set('kaoyanZhCacheV3',zhCache)}
function saveDict(){store.set('kaoyanDictCacheV3',dictCache)}
function gradeVocab(id,ok,{review=false,mode=currentMode}={}){const r=rec(id),wasSeen=r.seen>0,dueBefore=isDueRecord(r);r.seen++;r.last=today();r.lastResult=!!ok;r.lastMode=mode;P.done++;const d=daily();d.attempts++;if(!wasSeen)d.new++;if(review)d.review++;if(ok){r.correct++;d.correct++;r.wrongDebt=Math.max(0,(r.wrongDebt||0)-1);if(!wasSeen||dueBefore||review){const level=Math.min(r.level||0,INTERVALS.length-1);r.due=addDays(today(),INTERVALS[level]);r.level=Math.min((r.level||0)+1,INTERVALS.length)}}else{r.mistakes++;d.wrong++;r.wrongDebt=Math.min(12,(r.wrongDebt||0)+2);r.level=0;r.due=addDays(today(),1)}save();return r}
function markSentence(id,ok=true){P.sentences[id]=P.sentences[id]||{seen:0,correct:0,wrong:0};P.sentences[id].seen++;ok?P.sentences[id].correct++:P.sentences[id].wrong++;P.sentences[id].last=today();P.done++;daily().sentences++;save()}
function stableMastered(r){return !!(r&&r.seen>0&&(r.level||0)>=5&&(r.wrongDebt||0)===0)}
function updateHome(){const learned=Object.values(P.vocab).filter(r=>r.seen>0).length,due=dueItems(false).length,wrong=wrongItems(false).length,mastered=Object.values(P.vocab).filter(stableMastered).length,t=daily();$('#statTotal').textContent=lexicon.length.toLocaleString();$('#statLearned').textContent=learned.toLocaleString();$('#statDue').textContent=due.toLocaleString();$('#statWrong').textContent=wrong.toLocaleString();$('#statMastered').textContent=mastered.toLocaleString();$('#statToday').textContent=(t.review||0).toLocaleString();$('#dueInline').textContent=due.toLocaleString();const pct=learned?Math.round((Object.values(P.vocab).reduce((sum,r)=>sum+Math.min(1,(r.level||0)/5)*(r.seen>0?1:0),0)/lexicon.length)*100):0;$('#masteryPct').textContent=pct+'%';$('#masteryBar').style.width=pct+'%';const tomorrow=addDays(today(),1),tomorrowN=Object.values(P.vocab).filter(r=>r.due===tomorrow).length;$('#memorySummary').innerHTML=due?`今天有 <b>${due}</b> 个词到期；错题簿还有 <b>${wrong}</b> 个。你今天已经完成 <b>${t.review||0}</b> 次到期复习。`:`今天到期的词已经清空。错题簿还有 <b>${wrong}</b> 个；明天目前预计有 <b>${tomorrowN}</b> 个词到期。`;$('#corpusNote').innerHTML=`题库仍使用 2023—2026 四套英语一整卷：<b>${D.stats.lexical_total.toLocaleString()}</b> 个词汇/词组、<b>${D.stats.sentences_complete_8plus}</b> 个完整真题句。词汇记忆记录保存在当前网址对应的浏览器 LocalStorage 中；升级网页文件不会自动清空进度。建议偶尔点击右上角“导出记忆”备份。`}
function go(mode){currentMode=mode;$('#home').classList.remove('active');$('#trainer').classList.add('active');const meta={match:['VOCAB MATCH','词汇 / 词组连线'],'build-en':['SENTENCE BUILD','汉译 → 英文拼句'],'build-zh':['SENTENCE BUILD','英文 → 中文拼译'],free:['FREE TRANSLATION','无提示汉译'],structure:['SENTENCE ANATOMY','长难句拆骨架'],'spaced-review':['SPACED REVIEW','复习词汇 · 遗忘曲线'],review:['ERROR REVIEW','错题强化 · 真题语境填词']}[mode];$('#modeEyebrow').textContent=meta[0];$('#modeTitle').textContent=meta[1];renderYears();startMode()}
function renderYears(){$('#yearFilter').innerHTML=yearsAll.map(y=>`<button class="chip ${years.has(y)?'active':''}" data-y="${y}">${y}</button>`).join('');$$('[data-y]').forEach(b=>b.onclick=()=>{const y=+b.dataset.y;if(years.has(y)&&years.size>1)years.delete(y);else years.add(y);renderYears();startMode()})}
function yearsMatch(x){const ys=x.years||[x.year];return ys.some(y=>years.has(y))}
function startMode(){if(currentMode==='match')startMatch();else if(currentMode==='review'||currentMode==='spaced-review')startContextReview();else if(currentMode==='structure')startAnatomyHub();else startSentenceMode()}
const providers=['https://lingva.ml','https://translate.jae.fi','https://lingva.garudalinux.org','https://lingva.lunar.icu','https://translate.nexo.moe'];
function hasHan(s){return /[\u3400-\u9fff]/.test(s||'')}
async function fetchTimed(url,ms=5000){const ctl=new AbortController(),t=setTimeout(()=>ctl.abort(),ms);try{return await fetch(url,{signal:ctl.signal,cache:'force-cache'})}finally{clearTimeout(t)}}
async function translateText(text){text=(text||'').trim();if(!text)return '';const key='t|'+text;if(zhCache[key])return zhCache[key];for(const base of providers){try{const r=await fetchTimed(`${base}/api/v1/en/zh/${encodeURIComponent(text)}`,4500);if(!r.ok)continue;const j=await r.json();const z=(j.translation||'').trim();if(hasHan(z)){zhCache[key]=z;saveZh();return z}}catch(e){}}
try{const q=text.slice(0,450),r=await fetchTimed(`https://api.mymemory.translated.net/get?q=${encodeURIComponent(q)}&langpair=en|zh-CN`,5500);if(r.ok){const j=await r.json(),z=(j.responseData?.translatedText||'').trim();if(hasHan(z)){zhCache[key]=z;saveZh();return z}}}catch(e){}return ''}
function cleanGloss(z){return String(z||'').replace(/^(n\.|v\.|a\.|adj\.|adv\.|prep\.|conj\.|pron\.|num\.|art\.)\s*/i,'').split(/\n/)[0].slice(0,120)}
function isPhrase(term){return /\s/.test(term.trim())}
async function lookupDictionary(term){const key=term.toLowerCase();if(dictCache[key])return dictCache[key].miss?null:dictCache[key];if(isPhrase(term)){dictCache[key]={miss:true};saveDict();return null}try{const r=await fetchTimed(`https://api.dictionaryapi.dev/api/v2/entries/en/${encodeURIComponent(term)}`,4500);if(!r.ok){dictCache[key]={miss:true};saveDict();return null}const arr=await r.json(),entry=arr?.[0];const meanings=[];for(const m of entry?.meanings||[]){for(const d of (m.definitions||[]).slice(0,2)){if(d.definition)meanings.push({pos:m.partOfSpeech||'',definition:d.definition,example:d.example||''});if(meanings.length>=4)break}if(meanings.length>=4)break}const out={phonetic:entry?.phonetic||entry?.phonetics?.find(x=>x.text)?.text||'',meanings,source:entry?.sourceUrls?.[0]||''};dictCache[key]=out;saveDict();return out}catch(e){return null}}
async function zhLex(v){if(v.zh)return cleanGloss(v.zh);if(G.lexicon?.[v.term])return cleanGloss(G.lexicon[v.term]);const k='lex|'+v.term;if(zhCache[k])return zhCache[k];let z='';if(!isPhrase(v.term)){const de=await lookupDictionary(v.term);if(de?.meanings?.[0]?.definition){const dz=await translateText(de.meanings[0].definition);if(dz)z=cleanGloss(dz)}}if(!z)z=cleanGloss(await translateText(v.term));if(z){zhCache[k]=z;saveZh();return z}return '释义暂不可用'}
async function zhSentence(s){if(s.zh)return s.zh;if(G.sentences?.[s.id])return G.sentences[s.id];const k='sent|'+s.id;if(zhCache[k])return zhCache[k];const z=await translateText(s.en);if(z){zhCache[k]=z;saveZh();return z}return ''}
function weightedVocab(){const pool=lexicon.filter(yearsMatch),now=today();let bag=[];for(const v of pool){const r=P.vocab[v.id],unseen=!r?.seen,due=isDueRecord(r),debt=r?.wrongDebt||0;let wt=unseen?5:1;if(due)wt+=4;if(debt)wt+=debt*3;if(r?.last===now)wt=Math.max(1,Math.floor(wt/2));for(let i=0;i<Math.min(wt,30);i++)bag.push(v)}let out=[],used=new Set();for(const v of shuffle(bag)){if(!used.has(v.id)){out.push(v);used.add(v.id)}if(out.length===Math.min(50,pool.length))break}return out}
function startMatch(){session={items:weightedVocab(),group:0,score:0,answered:0};renderMatchGroup()}
async function renderMatchGroup(){const start=session.group*10,items=session.items.slice(start,start+10);if(!items.length){$('#trainerBody').innerHTML=`<div class="panel"><h2>本轮完成</h2><p>正确 ${session.score} / ${session.answered}</p><p class="muted-line">本轮第一次遇到的新词已自动加入后续复习计划；答错词同时进入错题簿。</p><div class="actions"><button class="primary" id="again">再来 50 个</button><button class="secondary" id="goDue">今日复习</button><button class="secondary" id="wrongOnly">错题强化</button></div></div>`;$('#again').onclick=startMatch;$('#goDue').onclick=()=>go('spaced-review');$('#wrongOnly').onclick=()=>go('review');return}$('#trainerBody').innerHTML='<div class="panel loading"><b>正在准备这一组词义…</b><span>优先采用内置人工/词典数据；其余单词会先查英英词典定义，再生成中文参考义并缓存。</span></div>';const zh=await Promise.all(items.map(zhLex));if(currentMode!=='match')return;const right=shuffle(items.map((x,i)=>({id:x.id,zh:zh[i]})));session.leftSel=null;session.rightSel=null;session.matched=new Set();$('#trainerBody').innerHTML=`<div class="panel"><div class="session-line"><span>本轮 ${session.items.length} · 第 ${session.group+1}/${Math.ceil(session.items.length/10)} 组</span><span>正确 ${session.score} / ${session.answered}</span></div><div class="match-grid"><div class="match-col">${items.map((x,i)=>{const r=P.vocab[x.id];const state=!r?.seen?'新词':isDueRecord(r)?'到期':(r.wrongDebt||0)>0?'错题':'已学';return `<button class="match-item" data-side="l" data-id="${x.id}"><b>${i+1}.</b> ${x.term}<small>${(x.years||[x.year]).join('/')} · ${x.type==='phrase'?'词组':'词汇'} · ${state}</small></button>`}).join('')}</div><div class="match-col">${right.map((x,i)=>`<button class="match-item" data-side="r" data-id="${x.id}"><b>${String.fromCharCode(97+i)}.</b> ${x.zh}</button>`).join('')}</div></div><div class="actions"><button class="secondary" id="nextGroup" disabled>下一组</button></div></div>`;$$('.match-item').forEach(b=>b.onclick=()=>selectMatch(b));$('#nextGroup').onclick=()=>{session.group++;renderMatchGroup()}}
function selectMatch(b){if(b.classList.contains('done'))return;const side=b.dataset.side;$$(`[data-side="${side}"]`).forEach(x=>x.classList.remove('selected'));b.classList.add('selected');session[side==='l'?'leftSel':'rightSel']=b;if(session.leftSel&&session.rightSel){const id=session.leftSel.dataset.id,ok=id===session.rightSel.dataset.id;session.answered++;gradeVocab(id,ok,{review:false,mode:'match'});if(ok){session.score++;[session.leftSel,session.rightSel].forEach(x=>{x.classList.remove('selected');x.classList.add('done')});session.matched.add(id)}else{[session.leftSel,session.rightSel].forEach(x=>{x.classList.add('wrongflash');setTimeout(()=>x.classList.remove('wrongflash','selected'),350)})}session.leftSel=session.rightSel=null;const groupN=Math.min(10,session.items.length-session.group*10);if(session.matched.size===groupN)$('#nextGroup').disabled=false}}
function sentencePool(){let p=D.sentences.filter(s=>years.has(s.year));if(currentMode==='structure')p=p.filter(s=>s.is_long);return p}
function startSentenceMode(){const pool=sentencePool();if(!pool.length)return;session={pool:shuffle(pool),idx:0};renderSentence()}
function nextSentence(){session.idx=(session.idx+1)%session.pool.length;renderSentence()}
async function renderSentence(){const s=session.pool[session.idx];if(currentMode==='build-en')await renderBuilder(s,'en');else if(currentMode==='build-zh')await renderBuilder(s,'zh');else if(currentMode==='free')await renderFree(s);else if(currentMode==='structure')await renderStructure(s)}
function autoEnChunks(text){let t=text.replace(/\s+/g,' ').trim();let parts=t.split(/(?<=[,;:])\s+|\s+(?=(?:but|and|while|although|because|if|when|which|who|that|where|as|since|so that|rather than|instead of|to)\b)/i).map(x=>x.trim()).filter(Boolean);if(parts.length<3){const words=t.split(' '),n=Math.max(5,Math.ceil(words.length/5));parts=[];for(let i=0;i<words.length;i+=n)parts.push(words.slice(i,i+n).join(' '))}return parts.slice(0,12)}
function autoZhChunks(z){let parts=z.split(/(?<=[，；：。！？])/).map(x=>x.trim()).filter(x=>x.length>1);if(parts.length<3){const cuts=['但是','因此','同时','而且','因为','尽管','从而','并且','以及','这意味着'];let t=z;for(const c of cuts)t=t.replaceAll(c,'|'+c);parts=t.split('|').map(x=>x.trim()).filter(x=>x.length>1)}if(parts.length<3&&z.length>24){const n=Math.ceil(z.length/4);parts=[];for(let i=0;i<z.length;i+=n)parts.push(z.slice(i,i+n))}return parts.slice(0,12)}
async function renderBuilder(s,lang){$('#trainerBody').innerHTML='<div class="panel loading"><b>正在准备真题句…</b></div>';const z=await zhSentence(s);if(!z)return showTranslateError(s);const correct=lang==='en'?(s.enChunks||autoEnChunks(s.en)):(s.zhChunks||autoZhChunks(z));const fixedDist=lang==='en'?['without changing the original conclusion','in spite of every possible outcome']:['这并不意味着所有问题都已解决','与此同时这一结论完全没有限制'];const distract=(lang==='en'?s.enDistractors:s.zhDistractors)||fixedDist,prompt=lang==='en'?z:s.en;session.answer=[];session.correct=correct;const bank=shuffle([...correct,...distract]).map((t,i)=>({key:'t'+i,text:t}));session.bank=bank;$('#trainerBody').innerHTML=`<div class="panel"><div class="sentence-meta"><span>${s.year} 英语一 · ${s.source} · P${s.page||'?'}</span><span>第 ${session.idx+1}/${session.pool.length} 句</span></div><div class="${lang==='en'?'prompt-cn':'prompt-en'}">${prompt}</div><div class="answer-zone" id="answerZone"><span class="placeholder">点击下方词块组成答案</span></div><div class="token-bank">${bank.map(t=>`<button class="token" data-key="${t.key}">${t.text}</button>`).join('')}</div><div class="actions"><button class="secondary" id="undo">撤回一步</button><button class="primary" id="checkBuild">检查</button><button class="secondary" id="nextSent">换一句</button></div><div id="buildFeedback"></div><div class="translation-note">${s.manual_translation?'Part C 人工校对译文':'非 Part C 句子的中文为训练参考译文；允许按意义理解，不要求逐字一致。'}</div></div>`;$$('.token').forEach(b=>b.onclick=()=>{if(b.classList.contains('used'))return;session.answer.push({key:b.dataset.key,text:b.textContent});b.classList.add('used');paintAnswer()});$('#undo').onclick=()=>{const x=session.answer.pop();if(x){document.querySelector(`[data-key="${x.key}"]`)?.classList.remove('used');paintAnswer()}};$('#checkBuild').onclick=()=>checkBuilder(s);$('#nextSent').onclick=nextSentence}
function paintAnswer(){const z=$('#answerZone');z.innerHTML=session.answer.length?session.answer.map((x,i)=>`<button class="token in-answer" data-ai="${i}">${x.text}</button>`).join(''):'<span class="placeholder">点击下方词块组成答案</span>';$$('[data-ai]').forEach(b=>b.onclick=()=>{const i=+b.dataset.ai,x=session.answer.splice(i,1)[0];document.querySelector(`[data-key="${x.key}"]`)?.classList.remove('used');paintAnswer()})}
function checkBuilder(s){const ans=session.answer.map(x=>x.text),target=session.correct,ok=ans.length===target.length&&ans.every((x,i)=>x===target[i]);markSentence(s.id,ok);$('#buildFeedback').innerHTML=`<div class="feedback ${ok?'good':'warn'}"><b>${ok?'✓ 完全正确':'还差一点'}</b><br>${ok?'语序和意群都对。':'参考顺序：'+target.join(' / ')}</div>`}
function norm(s){return (s||'').toLowerCase().replace(/[\s，。！？；：、“”‘’（）()\[\]【】,.!?;:'"—-]/g,'')}
function dice(a,b){a=norm(a);b=norm(b);if(!a||!b)return 0;const bi=s=>{let r=[];for(let i=0;i<s.length-1;i++)r.push(s.slice(i,i+2));return r};let A=bi(a),B=bi(b),m=0,used=new Array(B.length).fill(false);for(const x of A){let j=B.findIndex((y,k)=>!used[k]&&y===x);if(j>=0){used[j]=true;m++}}return (2*m)/(A.length+B.length||1)}
function semanticGroups(z){const chunks=autoZhChunks(z);return chunks.map(c=>{const n=c.replace(/[，。！？；：]/g,'').trim();return [n,n.replace(/^因此|^同时|^而且|^但是|^因为|^尽管/,'')]}).filter(g=>g[0].length>=3)}
function semanticScore(text,groups){const n=norm(text),hits=[];groups.forEach(g=>hits.push(g.some(x=>norm(x).length>=2&&n.includes(norm(x)))));return {coverage:groups.length?hits.filter(Boolean).length/groups.length:0,hits}}
async function renderFree(s){$('#trainerBody').innerHTML='<div class="panel loading"><b>正在准备参考译文…</b></div>';const z=await zhSentence(s);if(!z)return showTranslateError(s);session.refZh=z;$('#trainerBody').innerHTML=`<div class="panel"><div class="sentence-meta"><span>${s.year} 英语一 · ${s.source} · P${s.page||'?'}</span><span>${s.manual_translation?'Part C 人工校对':'宽松语义评分'}</span></div><div class="prompt-en">${s.en}</div><textarea class="textarea" id="freeInput" placeholder="直接写你的中文翻译。不要求和参考译文逐字一致……"></textarea><div class="actions"><button class="primary" id="scoreFree">宽松评分</button><button class="secondary" id="showRef">直接看参考译文</button><button class="secondary" id="nextSent">换一句</button></div><div id="freeFeedback"></div></div>`;$('#scoreFree').onclick=()=>scoreFree(s,z);$('#showRef').onclick=()=>{$('#freeFeedback').innerHTML=`<div class="feedback"><b>参考译文</b><br>${z}<div class="actions"><button class="primary" id="selfGood">我基本会了</button><button class="danger" id="selfBad">这句还不会</button></div></div>`;bindSelf(s)};$('#nextSent').onclick=nextSentence}
function bindSelf(s){const a=$('#selfGood'),b=$('#selfBad');if(a)a.onclick=()=>{markSentence(s.id,true);nextSentence()};if(b)b.onclick=()=>{markSentence(s.id,false);nextSentence()}}
function scoreFree(s,z){const text=$('#freeInput').value.trim();if(!text)return;const groups=s.groups||semanticGroups(z),sem=semanticScore(text,groups),sim=dice(text,z);let score=Math.round((sem.coverage*.35+sim*.65)*100);if(sim>.62)score=Math.max(score,78);if(sim>.72)score=Math.max(score,86);const cls=score>=80?'good':score>=55?'warn':'bad',label=score>=80?'核心意思基本到位':score>=55?'大意有较多重合':'建议再对照一次参考译文';markSentence(s.id,score>=55);$('#freeFeedback').innerHTML=`<div class="feedback ${cls}"><div class="score-row"><div class="score-ring">${score}</div><div><b>${label}</b><br><small>这是宽松辅助评分，不把参考译文当作唯一答案。你仍可自行修正判定。</small></div></div><hr><b>参考译文</b><br>${z}<div class="actions"><button class="primary" id="selfGood">我认为自己表达正确</button><button class="danger" id="selfBad">这句还不会</button></div></div>`;bindSelf(s)}
function autoStructure(en){const parts=autoEnChunks(en);return parts.map((p,i)=>{let label=i===0?'主干/起始分句':'分句/修饰';if(/^which\b|\bwhich\b/i.test(p))label='定语从句线索';else if(/^who\b|\bwho\b/i.test(p))label='关系从句线索';else if(/^that\b|\bthat\b/i.test(p))label='that 从句线索';else if(/^although\b|^though\b/i.test(p))label='让步关系';else if(/^because\b|^since\b/i.test(p))label='原因关系';else if(/^if\b|^unless\b/i.test(p))label='条件关系';else if(/^while\b|^whereas\b/i.test(p))label='对比/时间关系';else if(/^to\b/i.test(p))label='不定式结构';else if(/^but\b|^and\b/i.test(p))label='并列/转折连接';return `${label}：${p}`})}
async function renderStructure(s){$('#trainerBody').innerHTML='<div class="panel loading"><b>正在准备结构提示…</b></div>';const z=await zhSentence(s),structure=s.structure||autoStructure(s.en);$('#trainerBody').innerHTML=`<div class="panel"><div class="sentence-meta"><span>${s.year} 英语一 · ${s.source} · P${s.page||'?'}</span><span>${s.word_count} words</span></div><div class="prompt-en">${s.en}</div><button class="primary" id="revealStruct">显示句子骨架</button><div id="structArea"></div><div class="actions"><button class="secondary" id="nextSent">换一句</button></div></div>`;$('#revealStruct').onclick=()=>{$('#structArea').innerHTML=`<div class="structure-list">${structure.map((x,i)=>`<div class="structure-part"><b>${i+1}.</b> ${x}</div>`).join('')}</div>${z?`<div class="feedback"><b>参考译文</b><br>${z}</div>`:''}<div class="translation-note">${s.structure?'Part C 人工结构标注':'自动结构提示用于训练抓主干；复杂句最终以语义和上下文判断为准。'}</div>`;markSentence(s.id,true)};$('#nextSent').onclick=nextSentence}

let anatomyStage=null, anatomySession=null;
const anatomyTypeMeta={main:['主句 / 主干','主句主干'],object:['宾语 / 表语 / 内容从句','从句内容'],relative:['定语从句 / 后置定语','定语修饰'],adverbial:['状语 / 状语从句','状语修饰'],infinitive:['非谓语 / 不定式','非谓语'],modifier:['介词短语 / 其他修饰','修饰成分'],parenthetical:['插入 / 举例 / 解释','插入说明'],connector:['连接词 / 逻辑标记','逻辑连接']};
function anatomyRec(id){P.sentences[id]=P.sentences[id]||{seen:0,correct:0,wrong:0};P.sentences[id].anatomy=P.sentences[id].anatomy||{};return P.sentences[id]}
function markAnatomy(id,stage,ok){const r=anatomyRec(id),k=stage||'precise';r.anatomy[k]=r.anatomy[k]||{seen:0,correct:0,wrong:0};const x=r.anatomy[k];x.seen++;ok?x.correct++:x.wrong++;x.last=today();r.last=today();P.done++;daily().sentences++;save()}
function anatomyStats(){let a=0,b=0,c=0;for(const r of Object.values(P.sentences)){if(r.anatomy?.precise?.seen)a++;if(r.anatomy?.rough?.seen)b++;if(r.anatomy?.spine?.seen)c++}return [a,b,c]}
function startAnatomyHub(){anatomyStage=null;const [a,b,c]=anatomyStats();const precise=(AN.precise||[]).filter(x=>years.has(x.year)).length;const rough=Math.min(120,D.sentences.filter(s=>s.is_long&&years.has(s.year)&&!(AN.precise||[]).some(a=>a.id===s.id)).length);const spine=D.sentences.filter(s=>s.is_long&&years.has(s.year)).length;$('#trainerBody').innerHTML=`<div class="anatomy-intro"><div class="anatomy-philosophy"><span class="eyebrow">FROM FULL PARSING TO CORE SPINE</span><h2>先看透每个词，再逐步只抓主干。</h2><p>三个阶段不是重复做同一件事：第一阶段把句法结构拆到词；第二阶段只认分句和层级；第三阶段主动删掉修饰，把长句压缩成最短主干。</p></div><div class="anatomy-stage-grid"><button class="stage-card precise" data-an-stage="precise"><span>阶段 1 · 精拆</span><b>${precise} 句</b><h3>逐词归位</h3><p>每个英文单词都是一个小方块。把它放进“主句、宾语从句、定语从句、状语、非谓语、插入语……”对应区域；最后看结构树和汉译。</p><em>已练 ${a} 句 →</em></button><button class="stage-card rough" data-an-stage="rough"><span>阶段 2 · 强化</span><b>${rough} 句</b><h3>分句层级判断</h3><p>不再逐词抠细节。先把长句切成几大块，判断哪块是主句、哪块是从属或修饰，让眼睛形成“层级感”。</p><em>已练 ${b} 句 →</em></button><button class="stage-card spine" data-an-stage="spine"><span>阶段 3 · 主干</span><b>${spine} 句</b><h3>删修饰 → 缩句</h3><p>最后只做一件事：从长句里抓主语、谓语、宾语/表语，主动把句子压成最短核心意思。复杂细节不再纠缠。</p><em>已练 ${c} 句 →</em></button></div><div class="anatomy-goal"><b>最终能力：</b>看到 30—50 词长句，不需要完整语法标注，也能先在几秒内找到“谁 → 做什么 / 是什么 → 对谁/什么”，再决定要不要回看从句与修饰。</div></div>`;$$('[data-an-stage]').forEach(b=>b.onclick=()=>startAnatomyStage(b.dataset.anStage))}
function precisePool(){return (AN.precise||[]).filter(x=>years.has(x.year))}
function roughPool(){const ids=new Set((AN.precise||[]).map(x=>x.id));return D.sentences.filter(s=>s.is_long&&years.has(s.year)&&!ids.has(s.id)).sort((a,b)=>(b.word_count||0)-(a.word_count||0)).slice(0,120)}
function spinePool(){return D.sentences.filter(s=>s.is_long&&years.has(s.year))}
function startAnatomyStage(stage){anatomyStage=stage;let pool=stage==='precise'?precisePool():stage==='rough'?roughPool():spinePool();anatomySession={pool:shuffle(pool),idx:0,score:0};renderAnatomyStage()}
function anatomyNav(){return `<div class="anatomy-nav"><button class="secondary" id="anHub">← 三阶段</button><span>${anatomyStage==='precise'?'阶段 1 · 逐词精拆':anatomyStage==='rough'?'阶段 2 · 层级强化':'阶段 3 · 主干压缩'}</span></div>`}
function renderAnatomyStage(){if(!anatomySession?.pool?.length){$('#trainerBody').innerHTML='<div class="panel empty"><h2>当前年份筛选下没有可用句子</h2><button class="primary" id="anHub">返回三阶段</button></div>';$('#anHub').onclick=startAnatomyHub;return}if(anatomySession.idx>=anatomySession.pool.length)anatomySession.idx=0;const s=anatomySession.pool[anatomySession.idx];if(anatomyStage==='precise')renderPreciseAnatomy(s);else if(anatomyStage==='rough')renderRoughAnatomy(s);else renderSpineAnatomy(s)}
function nextAnatomy(){anatomySession.idx=(anatomySession.idx+1)%anatomySession.pool.length;renderAnatomyStage()}
function wordTokens(text){return (text.match(/[A-Za-z]+(?:[’'][A-Za-z]+)*|\d+(?:[.,]\d+)*/g)||[])}
function preciseTokens(a){let n=0,out=[];a.parts.forEach((p,pi)=>wordTokens(p.text).forEach(w=>out.push({id:'aw'+(n++),text:w,part:pi,type:p.type})));return out}
function renderPreciseAnatomy(a){const toks=preciseTokens(a);anatomySession.assign={};anatomySession.tokens=toks;$('#trainerBody').innerHTML=`${anatomyNav()}<div class="panel anatomy-panel"><div class="sentence-meta"><span>${a.year} 英语一 · Part C · 第 ${a.number} 题</span><span>${anatomySession.idx+1}/${anatomySession.pool.length} · ${toks.length} words</span></div><div class="an-step"><span>STEP 1</span><b>先读原句，不急着翻译</b></div><div class="prompt-en anatomy-source">${a.en}</div><div class="an-step"><span>STEP 2</span><b>逐词归位：每个单词都要有结构归属</b></div><p class="an-instruction">先点下面某个结构框，再点单词；也可以把单词拖进去。这里只判断“这个词属于哪一块”，不要求你重新排列整句。</p><div class="an-token-bank" id="anTokenBank">${toks.map(t=>`<button class="word-tile" draggable="true" data-tok="${t.id}">${t.text}</button>`).join('')}</div><div class="an-targets">${a.parts.map((p,i)=>`<div class="an-target type-${p.type}" data-part="${i}"><div class="target-head"><b>${p.label}</b><small>${anatomyTypeMeta[p.type]?.[0]||'结构成分'}</small></div><div class="drop-zone" data-part="${i}"><span class="drop-placeholder">把属于这一结构的单词放这里</span></div></div>`).join('')}</div><div class="actions"><button class="primary" id="anCheck">核对归位</button><button class="secondary" id="anHint">提示一个词</button><button class="secondary" id="anReveal">显示标准拆解</button><button class="secondary" id="anNext">换一句</button></div><div id="anFeedback"></div><div id="anRevealArea"></div></div>`;bindPreciseDnD(a)}
function bindPreciseDnD(a){let active=null;$$('.an-target').forEach(t=>{t.onclick=e=>{if(e.target.closest('.word-tile'))return;active=+t.dataset.part;$$('.an-target').forEach(x=>x.classList.toggle('active-target',x===t))};t.ondragover=e=>e.preventDefault();t.ondrop=e=>{e.preventDefault();const id=e.dataTransfer.getData('text/plain');moveAnToken(id,+t.dataset.part)}});$$('.word-tile').forEach(b=>{b.ondragstart=e=>e.dataTransfer.setData('text/plain',b.dataset.tok);b.onclick=e=>{e.stopPropagation();if(active!==null)moveAnToken(b.dataset.tok,active)}});$('#anCheck').onclick=()=>checkPrecise(a);$('#anHint').onclick=()=>hintPrecise(a);$('#anReveal').onclick=()=>revealPrecise(a);$('#anNext').onclick=nextAnatomy;$('#anHub').onclick=startAnatomyHub}
function moveAnToken(id,part){const b=document.querySelector(`[data-tok="${id}"]`),z=document.querySelector(`.drop-zone[data-part="${part}"]`);if(!b||!z)return;z.querySelector('.drop-placeholder')?.remove();z.appendChild(b);anatomySession.assign[id]=part;b.classList.remove('right-tile','wrong-tile')}
function checkPrecise(a){const toks=anatomySession.tokens;let right=0,placed=0;for(const t of toks){const b=document.querySelector(`[data-tok="${t.id}"]`),got=anatomySession.assign[t.id];if(got!==undefined)placed++;const ok=got===t.part;if(ok)right++;b?.classList.toggle('right-tile',ok);b?.classList.toggle('wrong-tile',got!==undefined&&!ok)}const pct=Math.round(right/toks.length*100);$$('.an-target').forEach(x=>{const i=+x.dataset.part,w=toks.filter(t=>t.part===i&&anatomySession.assign[t.id]!==i).length;x.classList.toggle('target-has-error',w>0)});$('#anFeedback').innerHTML=`<div class="feedback ${pct>=85?'good':pct>=55?'warn':'bad'}"><b>归位正确 ${right} / ${toks.length}（${pct}%）</b><br>${placed<toks.length?`还有 ${toks.length-placed} 个词没有放入结构框。`:'所有词都已经归位。'} ${pct>=85?'已经能看清这句话的层级了。':'先不要急着背答案，看看哪些词被你误判成了主干。'}</div>`;markAnatomy(a.id,'precise',pct>=70)}
function hintPrecise(a){const t=anatomySession.tokens.find(x=>anatomySession.assign[x.id]!==x.part);if(!t)return;moveAnToken(t.id,t.part);document.querySelector(`[data-tok="${t.id}"]`)?.classList.add('hint-tile');setTimeout(()=>document.querySelector(`[data-tok="${t.id}"]`)?.classList.remove('hint-tile'),900)}
function revealPrecise(a){for(const t of anatomySession.tokens)moveAnToken(t.id,t.part);const tree=a.parts.map((p,i)=>`<div class="structure-row type-${p.type}"><div class="structure-label"><b>${p.label}</b><small>${p.note||''}</small></div><div class="structure-words">${wordTokens(p.text).map(w=>`<span>${w}</span>`).join('')}</div></div>`).join('');$('#anRevealArea').innerHTML=`<div class="an-step"><span>STEP 3</span><b>标准结构地图</b></div><div class="structure-map">${tree}</div><div class="spine-box"><b>最短主干 / 主干化表达</b><div>${a.mainSpine}</div></div><div class="notes-box"><b>这一句最值得记住的拆法</b>${a.notes.map(x=>`<p>• ${x}</p>`).join('')}</div><div class="compression-box"><span>进一步缩句</span><b>${a.compressionEn}</b><small>${a.compressionZh}</small></div><div class="feedback good"><b>参考汉译</b><br>${a.zh}</div>`;markAnatomy(a.id,'precise',true)}
function splitRough(en){let chunks=en.replace(/—/g,', ').split(/[,;:]+/).map(x=>x.trim()).filter(Boolean);if(chunks.length<2){chunks=en.split(/\b(?:but|and|while|because|although|though|which|who|that|when|if)\b/i).map(x=>x.trim()).filter(Boolean)}return chunks.slice(0,8)}
function roughLabel(x,i){const s=x.trim();if(/^(if|unless|provided)/i.test(s))return '条件状语';if(/^(because|since|as)\b/i.test(s))return '原因/背景状语';if(/^(although|though|even if|while|whereas)\b/i.test(s))return '让步/对比';if(/^(when|before|after|until|once)\b/i.test(s))return '时间状语';if(/^(which|who|whose|where)\b/i.test(s))return '关系从句';if(/^to\b/i.test(s))return '不定式结构';if(/^by\s+\w+ing\b/i.test(s))return '方式状语';if(/^(however|therefore|instead|indeed|for example|in fact)/i.test(s))return '逻辑/插入';return i===0?'主句候选':'分句 / 修饰块'}
function renderRoughAnatomy(s){const chunks=splitRough(s.en),labels=chunks.map(roughLabel);anatomySession.roughChunks=chunks;anatomySession.roughLabels=labels;anatomySession.roughChoice=null;$('#trainerBody').innerHTML=`${anatomyNav()}<div class="panel anatomy-panel"><div class="sentence-meta"><span>${s.year} 英语一 · ${s.source} · P${s.page||'?'}</span><span>${anatomySession.idx+1}/${anatomySession.pool.length} · ${s.word_count} words</span></div><div class="an-step"><span>阶段 2</span><b>不再逐词：先看成几大块</b></div><div class="prompt-en anatomy-source">${s.en}</div><p class="an-instruction">下面是按标点和连接线索切出的“大块”。先选你认为最接近主句核心的一块，再看参考层级。这个阶段故意比精析粗。</p><div class="rough-chunks">${chunks.map((c,i)=>`<button class="rough-chunk" data-rough="${i}"><span>${i+1}</span>${c}</button>`).join('')}</div><div class="actions"><button class="primary" id="roughCheck">查看较粗分析</button><button class="secondary" id="anNext">换一句</button></div><div id="roughFeedback"></div></div>`;$$('[data-rough]').forEach(b=>b.onclick=()=>{$$('[data-rough]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');anatomySession.roughChoice=+b.dataset.rough});$('#roughCheck').onclick=async()=>{const mainIdx=Math.max(0,labels.findIndex(x=>x==='主句候选'));const cards=chunks.map((c,i)=>`<div class="rough-result ${i===mainIdx?'rough-main':''}"><b>${labels[i]}</b><span>${c}</span></div>`).join('');const z=await zhSentence(s);const ok=anatomySession.roughChoice===null?true:anatomySession.roughChoice===mainIdx;$('#roughFeedback').innerHTML=`<div class="structure-map rough-map">${cards}</div><div class="spine-box"><b>这一阶段只问自己三件事</b><div>① 哪块有真正的限定谓语？　② 哪些块只是 when / if / because / which / to / by 等引出的附加层？　③ 去掉它们以后，主句还能不能站住？</div></div>${z?`<div class="feedback"><b>参考汉译</b><br>${z}</div>`:''}<div class="translation-note">这是“较粗层级训练”，系统按标点和连接词给参考切分，不把它当成逐词语法判卷；复杂句回到阶段 1 精析思路处理。</div>`;markAnatomy(s.id,'rough',ok)};$('#anNext').onclick=nextAnatomy;$('#anHub').onclick=startAnatomyHub}
function roughSpine(en){let x=en.trim();x=x.replace(/^\s*(Although|Though|While|When|If|Because|Since|As|After|Before|Unless)\b[^,]{1,220},\s*/i,'');x=x.replace(/,\s*(which|who|whose|where)\b[^,]{1,220},/ig,',');x=x.replace(/,\s*(however|for example|in fact|indeed|of course)\s*,/ig,',');const first=x.split(/[;:]/)[0].trim();return first.length>220?first.slice(0,217)+'…':first}
function renderSpineAnatomy(s){const toks=wordTokens(s.en),ref=roughSpine(s.en);anatomySession.spineSelected=new Set();$('#trainerBody').innerHTML=`${anatomyNav()}<div class="panel anatomy-panel"><div class="sentence-meta"><span>${s.year} 英语一 · ${s.source} · P${s.page||'?'}</span><span>${anatomySession.idx+1}/${anatomySession.pool.length} · ${s.word_count} words</span></div><div class="an-step"><span>阶段 3</span><b>只抓主干：删掉能删的</b></div><div class="prompt-en anatomy-source">${s.en}</div><p class="an-instruction">点击你认为必须保留在“主干”里的词。你的目标不是做完整语法分析，而是尽快留下主语 + 限定谓语 + 必需宾语/表语。随后再把它缩写成一句更短的英语。</p><div class="spine-token-row">${toks.map((w,i)=>`<button class="word-tile spine-pick" data-sp="${i}">${w}</button>`).join('')}</div><textarea class="textarea spine-write" id="spineWrite" placeholder="可选：把原句缩写成一句最短英语。例如只保留“谁 + 做什么 / 是什么”。"></textarea><div class="actions"><button class="primary" id="spineReveal">查看参考主干</button><button class="secondary" id="anNext">换一句</button></div><div id="spineFeedback"></div></div>`;$$('[data-sp]').forEach(b=>b.onclick=()=>{const i=+b.dataset.sp;if(anatomySession.spineSelected.has(i)){anatomySession.spineSelected.delete(i);b.classList.remove('selected-spine')}else{anatomySession.spineSelected.add(i);b.classList.add('selected-spine')}});$('#spineReveal').onclick=async()=>{const precise=(AN.precise||[]).find(a=>a.id===s.id),r=precise?.mainSpine||ref,z=precise?.compressionZh||await zhSentence(s);$('#spineFeedback').innerHTML=`<div class="spine-box"><b>${precise?'人工精析主干':'参考主句候选（粗略）'}</b><div>${r}</div></div>${precise?`<div class="compression-box"><span>人工压缩句</span><b>${precise.compressionEn}</b><small>${precise.compressionZh}</small></div>`:''}<div class="notes-box"><b>最后一级的判断标准</b><p>• 去掉定语从句、状语从句、插入语、举例、介词修饰后，剩下部分必须仍然有主语和限定谓语。</p><p>• 不是越短越好；如果动词必须带宾语或表语，那个成分必须保留。</p><p>• 这一级不做逐词死板判错。你是在训练“先抓核心，再回头补细节”的阅读动作。</p></div>${z?`<div class="feedback"><b>核心意义参考</b><br>${z}</div>`:''}<div class="actions"><button class="primary" id="spineGood">我能抓住主干</button><button class="danger" id="spineBad">这句还不稳</button></div>`;$('#spineGood').onclick=()=>{markAnatomy(s.id,'spine',true);nextAnatomy()};$('#spineBad').onclick=()=>{markAnatomy(s.id,'spine',false);nextAnatomy()}};$('#anNext').onclick=nextAnatomy;$('#anHub').onclick=startAnatomyHub}

function escRe(s){return s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}
const contextCache={};
function termForms(v){return [...new Set([v.term,...(v.forms||[])])].filter(Boolean).sort((a,b)=>b.length-a.length)}
function termRegex(form){const e=escRe(form).replace(/\\\s+/g,'\\s+');return /^[A-Za-z][A-Za-z'-]*$/.test(form)?new RegExp(`\\b${e}\\b`,'i'):new RegExp(e,'i')}
function findPaperContext(v){if(contextCache[v.id])return contextCache[v.id];for(const form of termForms(v)){const re=termRegex(form);const hits=D.sentences.filter(s=>yearsMatch(s)&&re.test(s.en));if(hits.length){const same=hits.find(s=>s.year===v.year)||hits[0];contextCache[v.id]={text:same.en,year:same.year,source:same.source,page:same.page,form};return contextCache[v.id]}}const raw=(v.context||'').replace(/\s+/g,' ').trim();let text=raw;if(raw.length>440){let idx=-1,form=v.term;for(const f of termForms(v)){idx=raw.toLowerCase().indexOf(f.toLowerCase());if(idx>=0){form=f;break}}const a=Math.max(0,idx-180),b=Math.min(raw.length,idx+form.length+220);text=(a?'…':'')+raw.slice(a,b)+(b<raw.length?'…':'')}contextCache[v.id]={text,year:v.year,source:v.source,page:v.page,form:v.term};return contextCache[v.id]}
function makeBlank(v,c){let text=c.text;for(const form of termForms(v)){const re=termRegex(form);if(re.test(text))return text.replace(re,'_____')}return text+'  →  _____'}
function reviewPool(){if(currentMode==='spaced-review')return dueItems(true);return wrongItems(true)}
function startContextReview(){const pool=reviewPool();session={pool:currentMode==='spaced-review'?pool:shuffle(pool),idx:0,score:0,answered:0,kind:currentMode};renderContextReview()}
function chooseDistractors(v){const base=lexicon.filter(x=>x.id!==v.id&&x.type===v.type&&yearsMatch(x));const targetLen=v.term.length,rank=base.map(x=>({x,score:Math.abs(x.term.length-targetLen)+(x.year===v.year?0:2)})).sort((a,b)=>a.score-b.score).slice(0,80).map(o=>o.x);return sample(rank.length>=3?rank:base,3)}
async function renderContextReview(){const pool=session.pool;if(!pool.length){const isDue=currentMode==='spaced-review';$('#trainerBody').innerHTML=`<div class="panel empty"><h2>${isDue?'今天的到期复习已经完成':'目前没有需要强化的错题'}</h2><p>${isDue?'你可以继续学新词；新学词会自动安排到未来日期。':'先去做词汇连线，答错的词会自动进入这里。'}</p><div class="actions"><button class="primary" id="goMatch">去学新词</button>${isDue?'<button class="secondary" id="goWrong">看错题簿</button>':''}</div></div>`;$('#goMatch').onclick=()=>go('match');if($('#goWrong'))$('#goWrong').onclick=()=>go('review');return}if(session.idx>=pool.length){$('#trainerBody').innerHTML=`<div class="panel"><h2>${currentMode==='spaced-review'?'今日到期复习完成':'本轮错题强化完成'}</h2><p>本轮正确 ${session.score} / ${session.answered}。</p><div class="actions"><button class="primary" id="backNow">回首页</button><button class="secondary" id="againContext">再检查一轮</button></div></div>`;$('#backNow').onclick=()=>{$('#trainer').classList.remove('active');$('#home').classList.add('active');updateHome()};$('#againContext').onclick=startContextReview;return}const v=pool[session.idx],c=findPaperContext(v),blank=makeBlank(v,c),options=shuffle([v,...chooseDistractors(v)]);$('#trainerBody').innerHTML='<div class="panel loading"><b>正在从真题语境生成四选一…</b></div>';const headZh=await zhLex(v);if(currentMode!==session.kind)return;const r=rec(v.id),isDue=currentMode==='spaced-review';$('#trainerBody').innerHTML=`<div class="panel"><div class="session-line"><span>${c.year||v.year} · ${c.source||v.source}${c.page?' · P'+c.page:''}</span><span>${isDue?`到期 ${r.due} · 记忆级别 ${Math.min(r.level||0,INTERVALS.length)}`:`错题强度 ${r.wrongDebt||0}`} · ${session.idx+1}/${pool.length}</span></div><div class="context-box">${blank}</div><div class="option-grid context-options">${options.map((x,i)=>`<button class="option" data-id="${x.id}"><span class="opt-letter">${String.fromCharCode(65+i)}</span><b>${x.term}</b></button>`).join('')}</div><div id="reviewFeedback"></div><div class="actions"><button class="secondary" id="nextReview" disabled>下一题</button></div></div>`;$$('.option').forEach(b=>b.onclick=()=>answerContext(b,v,c,headZh,isDue));$('#nextReview').onclick=()=>{session.idx++;renderContextReview()}}
async function answerContext(b,v,c,zh,isDue){if($$('.option.correct,.option.wrong').length)return;const ok=b.dataset.id===v.id;b.classList.add(ok?'correct':'wrong');document.querySelector(`.option[data-id="${v.id}"]`)?.classList.add('correct');session.answered++;if(ok)session.score++;const rr=gradeVocab(v.id,ok,{review:isDue,mode:isDue?'spaced-review':'wrong-review'});$('#reviewFeedback').innerHTML=`<div class="feedback ${ok?'good':'warn'}"><b>${ok?'✓ 正确':'答案：'+v.term}</b><br><span class="muted-line">正在读取词典释义…</span></div>`;const de=await lookupDictionary(v.term);const next=rr.due?`下次复习：${rr.due}`:'尚未安排';let enDefs='';if(de?.meanings?.length)enDefs=`<div class="dict-defs">${de.meanings.slice(0,3).map(m=>`<div><span>${m.pos||'definition'}</span>${m.definition}${m.example?`<small>例：${m.example}</small>`:''}</div>`).join('')}</div>`;else enDefs=`<div class="dict-missing">${isPhrase(v.term)?'词组未必能在单词型英英词典中直接查到；这里保留真题语境和中文参考义。':'在线英英词典暂未返回该词条；不影响复习记录。'}</div>`;$('#reviewFeedback').innerHTML=`<div class="feedback ${ok?'good':'warn'}"><div class="dict-head"><div><b>${v.term}</b>${de?.phonetic?` <span class="phonetic">/${de.phonetic.replace(/^\/|\/$/g,'')}/</span>`:''}</div><span>${next}</span></div><div class="zh-meaning"><b>中文核心义：</b>${zh}</div><div class="truth-context"><b>真题原句：</b>${c.text}</div><div class="dict-title">英英词典释义</div>${enDefs}</div>`;$('#nextReview').disabled=false}
function showTranslateError(s){$('#trainerBody').innerHTML=`<div class="panel errorbox"><b>这一句的在线参考译文暂时没有取到。</b><p>原句仍已收录在本地语料库中。你可以换一句，或稍后重试；Part C 人工校对句不依赖在线翻译。</p><div class="prompt-en">${s.en}</div><div class="actions"><button class="primary" id="retry">重试</button><button class="secondary" id="nextSent">换一句</button></div></div>`;$('#retry').onclick=renderSentence;$('#nextSent').onclick=nextSentence}
function exportMemory(){const payload={app:'kaoyan-english-trainer',version:4,exportedAt:new Date().toISOString(),progress:P,zhCache,dictCache};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`kaoyan-memory-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function importMemoryFile(file){try{const data=JSON.parse(await file.text());if(!data?.progress||data.app!=='kaoyan-english-trainer')throw new Error('格式不正确');if(!confirm('导入会用备份中的学习记忆覆盖当前记忆，确定继续吗？'))return;P=normalizeProgress(data.progress);if(data.zhCache)zhCache=data.zhCache;if(data.dictCache)dictCache=data.dictCache;save();saveZh();saveDict();alert('记忆导入完成。')}catch(e){alert('导入失败：'+e.message)}}
$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
$('#backHome').onclick=()=>{$('#trainer').classList.remove('active');$('#home').classList.add('active');updateHome()};
$('#exportProgress').onclick=exportMemory;
$('#importProgress').onclick=()=>$('#importFile').click();
$('#importFile').onchange=e=>{const f=e.target.files?.[0];if(f)importMemoryFile(f);e.target.value=''};
$('#resetProgress').onclick=()=>{if(confirm('确定清空本机的所有练习记录吗？这不会删除题库。')){localStorage.removeItem('kaoyanProgressV3');P=blankProgress();save()}};
window.addEventListener('storage',e=>{if(e.key==='kaoyanProgressV3'){P=normalizeProgress(store.get('kaoyanProgressV3',blankProgress()));updateHome()}});
updateHome();
